<?php
// This file generated by Propel 1.6.8 convert-conf target
// from XML runtime conf file C:\Users\Daniel\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'geobin' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=geobin',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'geobin',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-geobin-conf.php');
return $conf;